### ISSUE TITLE
TLS connection fails due to improper socket.create_connection call

### ISSUE THREAD

**Issue by dlbewley** [Zimbra-Community/python-zimbra#20]
Test script based on [README.md](README.md) fails.

```
$ env python test.py
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    preauth_key[domain],
  File "/home/dlbewley/src/python-zimbra/venv/lib/python2.6/site-packages/pythonzimbra/tools/auth.py", line 104, in authenticate
    server.send_request(auth_request, response)
  File "/home/dlbewley/src/python-zimbra/venv/lib/python2.6/site-packages/pythonzimbra/communication.py", line 125, in send_request
    self.timeout
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/home/dlbewley/src/python-zimbra/venv/lib/python2.6/site-packages/pythonzimbra/tools/urllib2_tls.py", line 44, in https_open
    return self.do_open(TLS1Connection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1162, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.6/httplib.py", line 936, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 973, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 930, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 802, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 761, in send
    self.connect()
  File "/home/dlbewley/src/python-zimbra/venv/lib/python2.6/site-packages/pythonzimbra/tools/urllib2_tls.py", line 28, in connect
    self.timeout, self.source_address)
AttributeError: TLS1Connection instance has no attribute 'source_address'
```

PR coming.

**Comment by dploeger** [comment]
@dlbewley are you perhaps using Python 2.6? The source_address-parameter was added in Python 2.7 and python-zimbra is only compatible from Python 2.7 on.

**Comment by dlbewley** [comment]
Hmm. Yes, I'm on RHEL6 and Python 2.6.6. I haven't tested with 2.7, but I'll take your word for it.

**Comment by dploeger** [comment]
Yes, sorry. I know, that especially in enterprise linuxes, older python versions are available. Perhaps you can use [pyenv](https://github.com/yyuu/pyenv) to get to python 2.7 without breaking your system
