### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by sirio81** [Zimbra-Community/python-zimbra#34]
`cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"`

`python3 --version
Python 3.5.2`

`pip3 install python-zimbra
Traceback (most recent call last):
File "/usr/bin/pip3", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 12, in main
from pip._internal.utils.entrypoints import _wrapper
File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/entrypoints.py", line 4, in <module>
from pip._internal.cli.main import main
File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 58
sys.stderr.write(f"ERROR: {exc}")`

f-strings break compatibility with python version older than 3.6.

Home page says "Compatible with Python 2.7 and 3.x (cPython and PyPy)".

**Comment by sirio81** [comment]
Sorry, this seem to be relate to pip itself.
